matrix:
  user_id: "@shanzaychat:matrix.org"
  user_password: ""
  homeserver_url: "https://matrix.org"

database:
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
